; sram allocation

.equ freq1_l		= $0800
.equ freq1_h		= $0801
.equ freq2_l		= $0802
.equ freq2_h		= $0803
.equ freq3_l		= $0804
.equ freq3_h		= $0805
.equ freq4_l		= $0806
.equ freq4_h		= $0807
.equ attack			= $0808
.equ decay			= $0809
.equ last_byte		= $080a
.equ voice1			= $080b
.equ voice2			= $080c
.equ voice3			= $080d
.equ voice4			= $080e
.equ midi_channel 	= $080f
.equ decay_timer	= $0810
.equ bit_crush_l	= $0811
.equ bit_crush_h	= $0812
.equ pwm_depth1		= $0813
.equ pwm_depth2		= $0814
.equ pwm_depth3		= $0815
.equ pwm_depth4		= $0816
.equ freq_decay		= $0817
.equ cut_off		= $0818
.equ feedback		= $0819
.equ fm_freq		= $081a
.equ sweep_l		= $081b
.equ sweep_h		= $081c
.equ pwm_start		= $081d
.equ midi_state		= $081e
.equ fm_mod_l		= $081f
.equ fm_mod_h		= $0820
.equ am_freq		= $0821
.equ am_ptr			= $0822
.equ fm_count		= $0823
.equ cut_off_rev	= $0824


